### ISSUE TITLE
Test problems with dependency modules

### ISSUE THREAD

**Issue by DennisAhaus** [cayasso/cacheman#10]
Hi there,

thanks for your nice implementation. I think a found a problem with testing.

After browsing your test code i found an issue with testing dependency modules. You execute tests which should already be tested in the depedency module itself (like testing cacheman-mongodb engine). The problem is that if i do not have any mongodb/redis or other db instance on my test maschine i am not able to execute the tests successfully.

Another problem is that testing the dependency modules is like testing a database driver. I think the cacheman module tests should only test cacheman code itself and not the code of the dependency modules.

What do you think?

**Comment by cayasso** [comment]
Hey @DennisAhaus you are right, `cacheman` should only have `cacheman` stuff and we should test only the ability to receive a driver, we really don't need the dependencies here unless we would be testing integration. I will fix soon. Thanks for pointing this out.

**Comment by cayasso** [comment]
@DennisAhaus this commit addresses this issue https://github.com/cayasso/cacheman/commit/e053675ce8e15bc30b2fecdf174c0588f26757b0

Thanks for reporting!
