### ISSUE TITLE
Installation fails on Windows starting from 2.0.0

### ISSUE THREAD

**Issue by unbornchikken** [cayasso/cacheman#16]
package.json - postinstall - make: it is not available on Windows, so it fails to install. Please use something like gulp-traceur to compile ES6 files before publish to npm.

**Comment by mwalz** [comment]
Same problem on Linux servers on AWS when installing via npm install.

sh: 1: make: not found
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! cacheman@2.0.0 postinstall: `make`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cacheman@2.0.0 postinstall script 'make'.
npm ERR! This is most likely a problem with the cacheman package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make
npm ERR! You can get their info via:
npm ERR!     npm owner ls cacheman
npm ERR! There is likely additional logging output above.

**Comment by mwalz** [comment]
FYI, running `sudo apt-get install make` takes care of the problem on the server in the interim.

**Comment by cayasso** [comment]
Issue fixed by this commit https://github.com/cayasso/cacheman/commit/559473b3710c9b94324b1b7caef10a4938c0a2cc

release 2.0.1 is out

**Comment by unbornchikken** [comment]
Thanks for the support!
