### ISSUE TITLE
Occasionally create duplicate prefix cachecache:MYCACHENAME: 

### ISSUE THREAD

**Issue by murvinlai** [cayasso/cacheman#17]
Sometimes, it creates the cache key as:
 cachecache:mycachename:  
instead of
cache:mycachename: 

because when creating the Cacheman object, he option.prefix is used for both option._prefix (i.e. cache:mycachename: ) and the engine (Redis) prefix, and the default is "cache". 

so occasionally, in RedisClient, before issuing command, this.options.prefix is "cache", and it will append that to the agruments, which is "cache:mycachename", and becomes cachecache:mycachename:

better to have another options just for engine's prefix.

**Comment by ronenteva** [comment]
I have the same issue too.
@murvinlai did you find a workaround?

**Comment by murvinlai** [comment]
There is no work around. 
what i'm going to do is to fork it and change to have two prefix. one is for Cacheman, one is for passing to Redis Engine.

**Comment by cayasso** [comment]
@murvinlai @ronenteva This PR https://github.com/cayasso/cacheman/pull/19 fixed the issue, now the prefix setup makes more sense and should not cause the duplicate string in the key. 

It works like this now.

```js
    let c1 = new Cacheman();
    let c2 = new Cacheman('foo');
    let c3 = new Cacheman('foo', { prefix: 'myprefix' });

    assert.equal(c1._prefix, 'cacheman:cache:');
    assert.equal(c2._prefix, 'cacheman:foo:');
    assert.equal(c3._prefix, 'myprefix:foo:');
```

Please let me know if this works and if you see any more issues related to `prefix`.

**Comment by murvinlai** [comment]
Thanks.  I will try it out and test with my application this week.  :)

**Comment by murvinlai** [comment]
Seems like the same thing.

```
var Cacheman = require('cacheman');

var options = {
  ttl: 90,
  engine: 'redis',
  port: xxxx,
  host: "xxxx",
  prefix: 'test'
}

var cache = new Cacheman('todo', options);


cache.set('mykey', { a: 'bar' }, function (err, value) {
  if (err) throw err;
  console.log(value); //-> {a:'bar'}
});
```

Result is:

test:todo:test:todo:mykey
