### ISSUE TITLE
It still has duplicate prefix in the actual Redis DB

### ISSUE THREAD

**Issue by murvinlai** [cayasso/cacheman#26]
The latest version still has the duplicate prefix issue, not in the cacheman object (ie. cache._prefix) but in the actual redis DB.  

```
ie.  cacheman:todo:cacheman:todo:myKey
```

the problem is that when initializing the engine (e.g. cacheman-redis).   prefix is passed in.

and when doing the operations, e.g. set/get/del,  it will run this.key(key) before calling the engine's operation, which it will set the prefix again.

```
e.g. line 280 on lib/index.js
 this._engine.set(this.key(key), data, ttl || this._ttl, fn);
```

so either do not set the prefix to the engine.  
or this.key() do not append the prefix.

**Comment by murvinlai** [comment]
Considering others engine.. e.g. Cacheman-mongo, cacheman-file, etc has no "prefix" field in their class.  If cacheman operations want to append the prefix on those, but not cacheman-redis,  I suggest to do a check in key function.   e.g.:

```
key(key) {
    return (this.options.engine === 'redis')? key: this.prefix + key;
  }

```

**Comment by cayasso** [comment]
Fixed with PR above
