### ISSUE TITLE
Proposal: Get many keys

### ISSUE THREAD

**Issue by donnanicolas** [cayasso/cacheman#3]
I'm looking for a way to cache some things in a mongodb environment. But I need to retrieve many keys at the same time, 50 more or less. I know this is posible with in mongo, using the [$in](http://docs.mongodb.org/manual/reference/operator/query/in/) operator, in redis maybe with the [HMGET](http://redis.io/commands/hmget) and memory with multiple search. I didn't understand how the file one works, but I guess is not that hard to get from file multiple keys.

If you are ok with the idea, I could fork and do some pull requests

**Comment by cayasso** [comment]
Hi @donnanicolas sorry for the delay on this, sure, feel free to submit any pull requests you want if you are still interested in collaborating. 

I will close this issue and welcome any future PRs.
Best!
