### ISSUE TITLE
Wrap cache.get in setInterval()?

### ISSUE THREAD

**Issue by niczak** [cayasso/cacheman#34]
Hello there!

I am trying to check the cache every 100ms until I find the update I am expecting to be there.  For some reason the following code never resolves, is this something I am doing wrong or is there a better way for me to implement this type of solution?

```
exports.getCurrentValue = function(key) {
  console.log("In getCurrentValue Function:");

  return new Promise(function(resolve, reject) {
    var checkCache = function() {
      var time = new Date().valueOf();

      var interval = setInterval(function() {
        return cache.get(key)
          .then(function(value) {
            console.log("Checking cache...");
            console.dir(value);
            console.log("COMPARE: " + time + " -- " + value.time);
            if(typeof value != 'undefined' && value.time > time) {
              console.log("CONDITIONS MET");
              clearInterval(interval);
              return value;
            }
          });
      }, 100);
    }    

    checkCache()
      .then(function(value) {
        console.log("should be about to resolve..."); // This log never fires
        resolve(value);
      });
  });
}
```

I really appreciate your insight and this great library!

**Comment by cayasso** [comment]
@niczak  Just by looking at your code quickly I see that `checkCache` is not a `promise` but you are calling it like so, for it to return a `promise` you need to put the `promise` declaration within the `checkCache` function.
Also I would recommend not to use `setInterval` for this, I think it would be better to use `setTimeout` so you have more control when trying to exit your loop.

**Comment by niczak** [comment]
@cayasso Thank you for the quick response!  Your suggestion worked great and I am now able to resolve.

Thanks again!

**Comment by cayasso** [comment]
glad to help!!!
