### ISSUE TITLE
Override constructor TTL?

### ISSUE THREAD

**Issue by niczak** [cayasso/cacheman#35]
Hey there!

Is it possible to pass a different TTL which will override whatever was set in the constructor?

We want to keep most things in cache for 24-hours but there are some items which should be kept for a much shorter duration.  We instantiate cacheman by simply doing 

`var cache = new Cacheman({ttl:config.cacheTTL}); // config.cacheTTL = 24hours`

When I try to do a cache.set(key, data, ttl) ... it seems as if the TTL I pass here is ignored.  Am I doing something wrong or does cacheman not support this functionality?

Thanks!

**Comment by cayasso** [comment]
Strange this should work, can you try running the tests?.
This should succeed https://github.com/cayasso/cacheman/blob/master/test/index.js#L312

**Comment by niczak** [comment]
Very sorry, I was just passing a "numeric string" ('10') as opposed to '10s'.  When I change to that syntax it all works, life is good.

Thanks!
