### ISSUE TITLE
Pass already initialized clients as an engine

### ISSUE THREAD

**Issue by MatthewMueller** [cayasso/cacheman#5]
to share a single connection across the entire app.

**Comment by cayasso** [comment]
Hey @MatthewMueller this is added in master branch now, was a great feature to add, thanks!!

**Comment by MatthewMueller** [comment]
Hey buddy, thanks for the hasty fix!

Is this going to do it though? You should be able to do the following:

```js
var client = require('redis').createClient(opts);

// session storage
app.use(redisStorage({ client: client });

// caching
var cache = Cacheman(RedisEngine({ client: client }));

...
```

?

**Comment by cayasso** [comment]
@MatthewMueller not quite like that but like this:

```js
var engine = new RedisEngine({ client: client });
var cache = Cacheman('app', { engine: engine });

// or

var cache = Cacheman('app');
cache.engine(engine);
```

I am updating `cacheman-redis` to allow instantiating without the `new`. I also need to update `cacheman-mongo` to allow passing a mongodb instance. PR are also welcome :)

**Comment by cayasso** [comment]
@MatthewMueller actually you can now do this in `cacheman@1.1.0`:

```js
var client = require('redis').createClient(opts);

// session storage
app.use(redisStorage({ client: client });

// caching
var cache = Cacheman({ engine: RedisEngine(client) });
```

**Comment by MatthewMueller** [comment]
:heart
