### ISSUE TITLE
FR: a shortcut "wrap" function

### ISSUE THREAD

**Issue by rdiaztushman** [cayasso/cacheman#6]
Love the lib!  I'm probably going to use it.  

I have a single feature request (and if I can write it correctly, I will make a PR).  The FR is to add a "wrap" function similar to what they have here:
https://github.com/BryanDonovan/node-cache-manager#overview

I couldn't explain it any better than what's in their example.

**Comment by cayasso** [comment]
@rdiaztushman I like this functionality, I just added a comment for you to review, I think thats the only minor change before merging your contribution ;-)

**Comment by rdiaztushman** [comment]
Pull request has been updated.  Could you take a look and merge it in if all is OK?  Thanks!
