### ISSUE TITLE
Not necessarily an issue, just can't see a good use case for allowing undefined as a key.

### ISSUE THREAD

**Issue by nethermead** [cayasso/cacheman#9]
Had an issue with our backend where cacheman was caching things with bad keys (null and even undefined) without complaint.  Doing a fetch on null or undefined would return the most recent value, but I'm uncertain of the value of this behavior in general or if cacheman should at least complain a little.  It seems unintuitive that an undefined key would work at all.

I added some middleware to catch strange keys, but is there a reason to allow this in the first place?

**Comment by cayasso** [comment]
Fixed https://github.com/cayasso/cacheman/blob/master/lib/index.js#L263 @nethermead cacheman@1.1.1 is out.
